name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: re-shopping-cart-web-app
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_HUB_REPO: ${{ secrets.DOCKER_USERNAME }}/re-shopping-cart-web-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_HUB_REPO }}:latest -t ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_HUB_REPO }}:latest
          docker push ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_HUB_REPO: ${{ env.DOCKER_HUB_REPO }}
          DOCKER_IMAGE_NAME: ${{ env.DOCKER_IMAGE_NAME }}
        run: |
          echo "$EC2_SSH_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            # Login to Docker Hub
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || exit 1
          
            # Pull latest image
            docker pull $DOCKER_HUB_REPO:latest || exit 1
          
            # Stop and remove existing container
            docker stop $DOCKER_IMAGE_NAME || true
            docker rm $DOCKER_IMAGE_NAME || true
          
            # Check if .env.prod exists, if not warn but continue
            if [ ! -f .env.prod ]; then
              echo "Warning: .env.prod file not found. Container will start without env-file."
              ENV_FILE_FLAG=""
            else
              ENV_FILE_FLAG="--env-file .env.prod"
            fi
          
            # Run new container
            docker run -d \
              --name $DOCKER_IMAGE_NAME \
              --restart unless-stopped \
              -p 8080:8080 \
              $ENV_FILE_FLAG \
              $DOCKER_HUB_REPO:latest || exit 1
          
            # Clean up old images
            docker image prune -af --filter "until=168h"
          EOF
          rm -f ec2_key.pem

